import type { NodeType, RankId, SkillId } from "./types";

/**
 * Le matériel des laboratoires : vingt ans d'avance sur le monde.
 * Prêté pour une mission (dans la limite des fonds d'opération du grade), rendu au retour.
 */
export interface GadgetDef {
  id: string;
  name: string;
  description: string;
  skill: SkillId;
  bonus: number;
  /** Utilisations par mission (absent = illimité). */
  charges?: number;
  /** Coût de réquisition, imputé sur les fonds d'opération. */
  cost: number;
  /** Grade minimal pour le réquisitionner. */
  minRank: RankId;
  /** Niveau technologique : 1 et 2 disponibles d'emblée, 3 à débloquer par la recherche. */
  tier: 1 | 2 | 3;
  /** Étapes de mission où il ouvre une approche dédiée. */
  nodes: NodeType[];
  /** Effet immédiat quand il sert dans une étape. */
  effect?: { exposure?: number; alert?: number; intel?: number; health?: number };
}

export const GADGETS: GadgetDef[] = [
  {
    id: "lentilles",
    name: "Lentilles de réalité augmentée",
    description: "Reconnaissance faciale, traduction en direct, repérage des caméras et des angles morts.",
    skill: "regard",
    bonus: 2,
    cost: 800,
    minRank: "aspirant",
    tier: 1,
    nodes: ["renseignement", "filature", "approche"],
    effect: { intel: 1 },
  },
  {
    id: "micro_drones",
    name: "Essaim de micro-drones",
    description: "Douze drones de la taille d'une abeille : ils cartographient un bâtiment en quatre minutes.",
    skill: "regard",
    bonus: 2,
    charges: 2,
    cost: 3000,
    minRank: "agent",
    tier: 1,
    nodes: ["renseignement", "approche", "infiltration"],
    effect: { intel: 2 },
  },
  {
    id: "gants_gecko",
    name: "Gants gecko",
    description: "Adhérence moléculaire : on grimpe une façade de verre comme un escalier.",
    skill: "athletisme",
    bonus: 2,
    cost: 1500,
    minRank: "aspirant",
    tier: 1,
    nodes: ["infiltration", "effraction", "extraction"],
  },
  {
    id: "montre_emp",
    name: "Montre à impulsion électromagnétique",
    description: "Une fois : toute l'électronique dans un rayon de vingt mètres s'éteint pendant trente secondes.",
    skill: "machine",
    bonus: 3,
    charges: 1,
    cost: 2000,
    minRank: "agent",
    tier: 1,
    nodes: ["effraction", "piratage", "combat", "extraction"],
    effect: { alert: -10 },
  },
  {
    id: "passe_quantique",
    name: "Passe quantique",
    description: "Ouvre en quelques secondes n'importe quelle serrure électronique du marché.",
    skill: "doigte",
    bonus: 3,
    charges: 3,
    cost: 2500,
    minRank: "agent",
    tier: 1,
    nodes: ["effraction", "infiltration"],
  },
  {
    id: "stylo_sedatif",
    name: "Stylo-seringue sédatif",
    description: "Une pression, dix minutes de sommeil sans souvenir.",
    skill: "combat",
    bonus: 2,
    charges: 3,
    cost: 600,
    minRank: "aspirant",
    tier: 1,
    nodes: ["combat", "objectif", "extraction"],
    effect: { alert: -5 },
  },
  {
    id: "modulateur",
    name: "Modulateur vocal",
    description: "Implant sous la mâchoire : n'importe quelle voix entendue plus de dix secondes.",
    skill: "masque",
    bonus: 2,
    cost: 1200,
    minRank: "aspirant",
    tier: 1,
    nodes: ["social", "infiltration", "piratage"],
  },
  {
    id: "verres_thermiques",
    name: "Verres thermiques",
    description: "Lunettes de soleil ordinaires… qui voient à travers les cloisons.",
    skill: "alerte",
    bonus: 2,
    cost: 1000,
    minRank: "aspirant",
    tier: 1,
    nodes: ["combat", "infiltration", "poursuite"],
  },
  {
    id: "traceurs",
    name: "Traceurs nanométriques",
    description: "Une poudre invisible : chaque grain émet sa position pendant trois jours.",
    skill: "regard",
    bonus: 2,
    charges: 4,
    cost: 1200,
    minRank: "aspirant",
    tier: 1,
    nodes: ["filature", "renseignement", "social"],
    effect: { intel: 1 },
  },
  {
    id: "kit_nanosuture",
    name: "Kit de nanosuture",
    description: "Referme une plaie par balle en deux minutes. Ça brûle.",
    skill: "medecine",
    bonus: 3,
    charges: 2,
    cost: 1500,
    minRank: "aspirant",
    tier: 1,
    nodes: ["complication", "extraction", "combat"],
    effect: { health: 3 },
  },
  {
    id: "masque_memoire",
    name: "Masque à mémoire de forme",
    description: "Copie un visage en quarante secondes, tient six heures.",
    skill: "masque",
    bonus: 3,
    charges: 2,
    cost: 4000,
    minRank: "agent",
    tier: 2,
    nodes: ["social", "infiltration", "objectif"],
    effect: { exposure: -10 },
  },
  {
    id: "camouflage",
    name: "Combinaison à camouflage actif",
    description: "Des millions de micro-écrans reproduisent ce qu'il y a derrière toi. Parfait dans la pénombre.",
    skill: "ombre",
    bonus: 3,
    charges: 2,
    cost: 6000,
    minRank: "agent",
    tier: 2,
    nodes: ["infiltration", "effraction", "extraction", "filature"],
    effect: { exposure: -10 },
  },
  {
    id: "cle_ia",
    name: "Clé d'intrusion autonome",
    description: "Une IA de la taille d'un ongle : branchée trente secondes, elle ouvre le réseau de l'intérieur.",
    skill: "machine",
    bonus: 3,
    charges: 2,
    cost: 3500,
    minRank: "agent",
    tier: 2,
    nodes: ["piratage", "renseignement", "objectif"],
    effect: { intel: 1 },
  },
  {
    id: "hologramme",
    name: "Projecteur holographique",
    description: "Un leurre en trois dimensions : toi, ailleurs, pendant vingt secondes.",
    skill: "vivacite",
    bonus: 2,
    charges: 2,
    cost: 5000,
    minRank: "agent",
    tier: 2,
    nodes: ["poursuite", "combat", "extraction"],
    effect: { alert: -15 },
  },
  {
    id: "brouilleur",
    name: "Brouilleur de poche",
    description: "Coupe téléphones, radios et caméras sans fil d'un étage entier.",
    skill: "machine",
    bonus: 2,
    charges: 2,
    cost: 1800,
    minRank: "agent",
    tier: 1,
    nodes: ["infiltration", "piratage", "extraction"],
    effect: { alert: -10 },
  },
  {
    id: "capsule_oubli",
    name: "Capsule d'oubli",
    description: "Un gaz qui efface les vingt dernières minutes de mémoire de ceux qui le respirent.",
    skill: "eloquence",
    bonus: 2,
    charges: 1,
    cost: 4000,
    minRank: "titulaire",
    tier: 2,
    nodes: ["social", "complication", "extraction"],
    effect: { exposure: -25 },
  },
  {
    id: "exosquelette",
    name: "Exosquelette souple",
    description: "Se porte sous un costume. Triple ta force pendant dix minutes.",
    skill: "force",
    bonus: 3,
    charges: 2,
    cost: 8000,
    minRank: "titulaire",
    tier: 3,
    nodes: ["combat", "effraction", "extraction"],
  },
  {
    id: "wingsuit",
    name: "Wingsuit à micro-réacteurs",
    description: "Pliée dans un sac de sport. Décolle d'un toit, se pose à douze kilomètres.",
    skill: "pilotage",
    bonus: 3,
    charges: 1,
    cost: 9000,
    minRank: "titulaire",
    tier: 3,
    nodes: ["extraction", "poursuite", "approche"],
    effect: { alert: -10 },
  },
  {
    id: "voiture_amphibie",
    name: "Voiture amphibie",
    description: "Berline de luxe en apparence ; sous-marin de poche à la demande.",
    skill: "pilotage",
    bonus: 3,
    cost: 15000,
    minRank: "titulaire",
    tier: 3,
    nodes: ["poursuite", "extraction", "approche"],
  },
  {
    id: "lame_monofilament",
    name: "Montre à fil monomoléculaire",
    description: "Un fil invisible qui tranche l'acier. Ne jamais le toucher.",
    skill: "precision",
    bonus: 3,
    charges: 2,
    cost: 7000,
    minRank: "doyen",
    tier: 3,
    nodes: ["effraction", "combat", "objectif"],
  },
];

export const findGadget = (id: string | undefined) => GADGETS.find((g) => g.id === id);
